sudo: required

language: python

matrix:
  include:
    - python: "3.7"
      env: TOX=py37
    - python: "3.6"
      env: TOX=py36
    - python: "3.6"
      env: TOX=no
    - python: "3.6"
      env: TOX=infra

install:
  - |
    if [ "$TOX" = "no" ]; then
      pip install https://github.com/ome/zeroc-ice-py-manylinux/releases/download/0.1.0/zeroc_ice-3.6.5-cp36-cp36m-manylinux2010_x86_64.whl
      pip install restructuredtext-lint
    elif [ "$TOX" = "infra" ]; then
      git clone git://github.com/ome/omero-test-infra .omero
    else
      pip install tox
    fi

script:
  - |
    if [ "$TOX" = "no" ]; then
      rst-lint README.rst
      python setup.py sdist
      pip install dist/omero-dropbox*gz
      omero version
    elif [ "$TOX" = "infra" ]; then
      .omero/docker scripts
    else
      tox -e $TOX
    fi

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: "$TOX = no"
