---
name: Build
on:
  schedule:
    - cron: '0 0 * * 0'
  push:
  pull_request:

jobs:
  test_tox:
    name: Run tox tests
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -mpip install --upgrade wheel pytest tox
      - name: Get tox target
        id: toxtarget
        run: |
          py=$(echo ${{ matrix.python-version }} | tr -d .)
          echo "::set-output name=py::$py"
      - name: Run tests
        run: tox -e py${{ steps.toxtarget.outputs.py }}

  test_infra:
    name: Run integration tests against OMERO
    runs-on: ubuntu-latest
    env:
      STAGE: scripts # app, cli, lib, scripts, srv
    steps:
      - uses: actions/checkout@v2
      - name: Checkout omero-test-infra
        uses: actions/checkout@master
        with:
          repository: ome/omero-test-infra
          path: .omero
          ref: ${{ secrets.OMERO_TEST_INFRA_REF }}
      - name: Build and run OMERO tests
        run: .omero/docker $STAGE

  publish-pypi:
    name: Pypi
    if: startsWith(github.ref, 'refs/tags')
    needs:
      # Only publish if other jobs passed
      - test_tox
      - test_infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Set up
        run: |
          pip install https://github.com/ome/zeroc-ice-py-manylinux/releases/download/0.1.0/zeroc_ice-3.6.5-cp36-cp36m-manylinux2010_x86_64.whl
      - name: Build package
        run: |
          python -mpip install wheel
          python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.3.0
        with:
          password: ${{ secrets.PYPI_PASSWORD }}
